[project]
name = "cs217-final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lm-eval[hf] @ file://${PROJECT_ROOT}/third_party/lm-evaluation-harness",
]

[tool.setuptools]
packages = ["experiments"]
